site_name: "Power metrics library"

theme:
  name: "readthedocs"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            heading_level: 2
            show_root_heading: true
            show_source: false

nav:
  - index.md
  - activities.md
  - workouts.md
  - reference.md

watch:
  - src/power_metrics_lib
