site_name: "Training watt library"

theme:
  name: "readthedocs"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 2
            show_root_heading: true
            show_source: false

nav:
  - index.md
  - reference.md

watch:
  - power_metrics_lib
